"""COMPOSE-FM: the general composition operator. NO domain vocabulary in this file.

The method answers a question that is domain-independent: given flows that each realise a
single intervention, what flow realises several interventions applied together, at exposures
outside the observed range?

    Objects:  latent state z in R^d
              interventions p in {1..P}, each with a learned autonomous generator X_p(z)
              exposure tau_p >= 0, the parameter of the one-parameter family generated by X_p

    Operator (Eq. 1 of the paper):

        X_P(z) = gamma(z, P) * sum_p tau_p X_p(z)                 [contraction gate]
                 + 1/2 sum_{p<q} beta_pq(z) S^grad_pq(z)          [coupling]

        S^grad_pq(z) = DX_q(z) X_p(z) + DX_p(z) X_q(z) + 2 Gamma(z)[X_p, X_q]

    and the prediction is the flow of X_P for unit time:  z(1) = phi^1_{X_P}(z(0)).

Three design commitments, each with a reason that is not about any dataset:

1. COMPOSE GENERATORS, NOT DISPLACEMENTS. Summing displacements phi_p(z) - z is not a
   chart-independent operation: under a diffeomorphism psi the displacement transforms with
   O(||d||^2) error, so a model that adds displacements gives different answers in different
   latent coordinates. Summing vector fields is exactly covariant. Verified numerically:
   field sum error 5.5e-17, displacement sum error 1.7e-3 (results/gate_a.json,
   results/gate_a2.json).

2. EXPOSURE IS INTEGRATION TIME. Because each X_p is autonomous, the flow satisfies the
   semigroup property phi^{s+t} = phi^s o phi^t by construction, so exposure extrapolation
   is a structural property rather than a fitted one. This is what a displacement model
   cannot do: it must learn each exposure separately.

   PRECISE STATEMENT (measured, not assumed). Integrating a FIXED field for time s+t
   equals integrating for s then t: verified at 2.3e-7 relative error (= RK2 integration
   error at 400 steps), i.e. exact up to the solver. The weaker statement "scaling tau by
   c equals scaling time by c" is only approximate -- 3.6e-5 here -- because gamma(z, P)
   depends on tau, so a change of exposure slightly changes the field's shape as well as
   its magnitude. The semigroup guarantee therefore applies to the exposure-parameterised
   FLOW, and the paper must state it that way; claiming exact tau-scaling would be false.

3. THE COUPLING TERM IS THE COVARIANT SYMMETRISATION. The naive symmetric field
   DX_q X_p + DX_p X_q is NOT a tensor (pushforward-vs-native discrepancy ~1e-1); adding
   the Levi-Civita connection term restores exact tensoriality (~1e-11). The antisymmetric
   part -- the Lie bracket -- is already tensorial (~1.7e-16), which is why bracket-based
   methods do not face this problem and why the symmetric part needs the correction.
"""
from __future__ import annotations
import math
import torch
import torch.nn as nn


# --------------------------------------------------------------------------- utils
def mlp(i, h, o, depth=2, act=nn.SiLU, ln=False):
    layers, d = [], i
    for _ in range(depth):
        layers += [nn.Linear(d, h)]
        if ln:
            layers += [nn.LayerNorm(h)]
        layers += [act()]
        d = h
    layers += [nn.Linear(d, o)]
    return nn.Sequential(*layers)


class PopulationEncoder(nn.Module):
    """Permutation-invariant code for the PRE-INTERVENTION STATE DISTRIBUTION.

    Why the operator needs this (measured, and it is a structural point rather than a
    tuning trick). The generators X_p(z) are functions of a single state z, so two
    populations that occupy overlapping regions of state space but respond in DIFFERENT
    directions to the same intervention cannot both be fitted. That is not hypothetical:
    on the organoid ladder the mean pairwise cosine between the response directions of
    different replicates of the SAME treatment is only +0.35 (S), +0.23 (F), +0.34 (CSF).
    A model conditioned only on (intervention, exposure) must average over those
    directions, and duly scores WORSE than predicting no change in-distribution
    (normalised energy distance 1.08-1.12), while the same architecture fitted to a single
    population reaches 0.032. The missing conditioning variable is the population itself.

    So we condition the operator on a code u = rho(mean_i phi(z_i)) computed from the
    pre-intervention sample -- a DeepSets encoder, hence permutation-invariant and
    independent of the sample size. The composition operator becomes

        X_P(z; u) = gamma(z, P, u) sum_p tau_p X_p(z; u) + 1/2 sum beta_pq(z, u) S_pq(z; u)

    and every structural property is preserved: u is CONSTANT along the flow of a given
    population, so each X_p(.; u) is still an autonomous vector field and the exposure
    semigroup still holds exactly.

    Relation to prior work. Conditioning a flow on its own population is the contribution
    of Meta Flow Matching (Atanackovic et al., arXiv:2408.14608, ICLR 2025), which embeds
    the population and conditions ONE velocity field on it. We use the same conditioning
    idea and must cite it as such; what is new here is not the conditioning but the
    COMPOSITION of several conditioned generators, with the contraction and coupling terms
    that let unseen intervention SETS and unseen exposures be predicted. MFM does not
    compose interventions.

    MEASURED OUTCOME -- DEFAULT OFF (code=0). On the organoid ladder this component does
    NOT pay for itself and we report that rather than quietly shipping it. With the full
    control population encoded (800 cells, LayerNormed code, 800 training steps):

        pop_code = 0    train 1.0915    held-out triple 0.9027
        pop_code = 16   train 1.0803    held-out triple 1.2831

    It buys a marginal in-distribution gain and materially DAMAGES the extrapolation that
    the paper is about. The diagnosis is small-sample overfitting to replicate identity:
    the control mean does carry real signal about the response direction (leave-one-out R2
    +0.29 / +0.32 / +0.21 for S / F / CSF, mean cosine to the true shift rising 0.591 ->
    0.701 for S and 0.482 -> 0.594 for F over a global mean shift), but with only 26
    held-out triple populations the encoder memorises which replicate it is looking at
    instead of learning that mapping. The honest conclusion is that population conditioning
    needs either many more populations or an explicit invariance penalty; it is kept in the
    codebase, off by default, as a documented negative result and a clean follow-up.
    """

    def __init__(self, d, code=16, hidden=64, use_second_moment=True):
        super().__init__()
        self.use_second_moment = use_second_moment
        in_dim = d * (2 if use_second_moment else 1)
        self.phi = mlp(in_dim, hidden, hidden, depth=2)
        self.rho = mlp(hidden, hidden, code, depth=2)
        self.norm = nn.LayerNorm(code)
        self.code = code

    def forward(self, z_pop):
        """z_pop: (N, d) sample from the pre-intervention distribution -> (code,)

        LayerNorm on the output matters: without it the code's scale drifts with the
        sample size and the downstream networks -- whose inputs are unit-scaled states --
        effectively ignore it. The pooled statistic must also be computed over as much of
        the population as is available, not over the small minibatch used for the loss:
        the informative signal here is the population MEAN (control mean predicts the
        response direction with LOO R2 +0.29 / +0.32 / +0.21 on S / F / CSF), and a
        256-cell subsample dilutes it.
        """
        h = torch.cat([z_pop, z_pop ** 2], -1) if self.use_second_moment else z_pop
        return self.norm(self.rho(self.phi(h).mean(0)))


class Generators(nn.Module):
    """Per-intervention autonomous vector fields X_p(z), as one conditioned network.

    A shared trunk with a learned per-intervention embedding, so interventions share
    structure (most of what a perturbation does is not unique to it) while keeping their
    own direction field.

    Init note (this cost a debugging cycle, so it is recorded): the output layer must be
    SMALL but NOT zero. Zero-initialising it makes every X_p identically zero, which makes
    the summed drive zero, which makes the gate's input constant and the coupling term
    vanish -- so gradient reaches only the last layer and the model never starts. Measured:
    2 of 40 parameter tensors received gradient. A small nonzero gain keeps the flow near
    the identity at init while leaving every path differentiable.
    """

    def __init__(self, d, n_pert, emb=32, hidden=128, depth=3, ln=True,
                 out_gain=1e-2, code=0):
        super().__init__()
        self.d, self.n_pert, self.code = d, n_pert, code
        self.emb = nn.Embedding(n_pert, emb)
        nn.init.normal_(self.emb.weight, std=0.1)
        self.net = mlp(d + emb + code, hidden, d, depth=depth, ln=ln)
        nn.init.normal_(self.net[-1].weight, std=out_gain)
        nn.init.zeros_(self.net[-1].bias)

    def forward(self, z, p, u=None):
        """z: (B,d); p: int or (B,) long; u: (code,) or (B,code) -> (B,d)"""
        if not torch.is_tensor(p):
            p = torch.full((z.shape[0],), int(p), device=z.device, dtype=torch.long)
        parts = [z, self.emb(p)]
        if self.code:
            parts.append(u.expand(z.shape[0], -1) if u.dim() == 1 else u)
        return self.net(torch.cat(parts, -1))

    def all_fields(self, z, ps, u=None):
        """-> (B, k, d) for a list/tensor of intervention ids."""
        return torch.stack([self(z, p, u) for p in ps], dim=1)


class ContractionGate(nn.Module):
    """gamma(z, P) in (0, 1]: how much the summed drive is attenuated in state z.

    Rationale (domain-free): interventions act through shared downstream capacity, so their
    joint effect generally falls short of the sum of their separate effects. The gate is a
    scalar function of the state AND of the intervention set, built from a permutation-
    invariant (sum) encoding of the active generators so it does not depend on their order.

    SATURATING FORM (this is the part that makes exposure extrapolation work). A gate that
    only multiplies the summed drive by a number in (0,1) still leaves the drive GROWING
    LINEARLY in total exposure, so at exposures far outside the training range the flow
    diverges: measured normalised energy distance 10.4 (displacement), 10.9 (plain fields)
    and 8.0 (multiplicative gate only) at an 8.7x exposure extrapolation, versus 1.00 for
    predicting no change. That is a structural failure, not a fitting error.

    We therefore give the gate an explicit saturating dependence on total exposure:

        gamma(z, P) = g_state(z, P) * (1 + (T / kappa(z))^nu)^(-1)      T = sum_p tau_p

    with kappa > 0 and nu > 0 learned (nu via softplus, so the exponent stays positive).
    Then ||X_P|| ~ T^(1-nu) for T >> kappa: the operator can represent a saturating
    response law with a LEARNED exponent rather than assuming one. Setting nu ~ 0.5
    recovers a square-root response, which is the empirically established scaling of price
    impact in executed quantity (measured on this data: bin-mean log-log slope 0.587) and
    of dose-response saturation in pharmacology. Neither is assumed: nu is fitted.

    Note this keeps the gate a function of (state, intervention set, total exposure) only --
    no domain quantity enters, and the same form is used in every case study.
    """

    def __init__(self, d, emb=32, hidden=64, learn_scale=True, saturate=True,
                 nu_init=0.5, kappa_init=1.0, code=0):
        super().__init__()
        self.code = code
        self.net = mlp(d + d + 2 + code, hidden, 1, depth=2)
        nn.init.normal_(self.net[-1].weight, std=1e-2)   # small, NOT zero (see Generators)
        nn.init.constant_(self.net[-1].bias, 2.2)        # sigmoid(2.2) ~ 0.9: near-additive
        self.log_scale = nn.Parameter(torch.zeros(())) if learn_scale else None
        self.saturate = saturate
        if saturate:
            # kappa(z) = softplus(head(z)) + eps : exposure scale at which saturation bites
            self.kappa_head = mlp(d, hidden // 2, 1, depth=1)
            nn.init.normal_(self.kappa_head[-1].weight, std=1e-2)
            nn.init.constant_(self.kappa_head[-1].bias, float(kappa_init))
            # nu = softplus(raw): the saturation exponent, learned
            inv = math.log(math.expm1(nu_init)) if nu_init > 0 else -3.0
            self.nu_raw = nn.Parameter(torch.tensor(float(inv)))

    def forward(self, z, fields, taus, u=None):
        """z (B,d); fields (B,k,d); taus (B,k); u (code,) -> (B,1)"""
        drive = (taus.unsqueeze(-1) * fields).sum(1)              # (B,d) summed drive
        k = taus.gt(0).sum(-1, keepdim=True).float()
        tot = taus.sum(-1, keepdim=True)
        parts = [z, drive, k, tot]
        if self.code:
            parts.append(u.expand(z.shape[0], -1) if u.dim() == 1 else u)
        h = torch.cat(parts, -1)
        g = torch.sigmoid(self.net(h))
        if self.log_scale is not None:
            g = g * torch.exp(self.log_scale).clamp(max=2.0)
        if self.saturate:
            kappa = torch.nn.functional.softplus(self.kappa_head(z)) + 1e-3
            nu = torch.nn.functional.softplus(self.nu_raw) + 1e-4
            g = g / (1.0 + (tot.clamp(min=0) / kappa) ** nu)
        return g

    def exponent(self):
        """The learned saturation exponent nu (for reporting)."""
        if not self.saturate:
            return float("nan")
        with torch.no_grad():
            return float(torch.nn.functional.softplus(self.nu_raw) + 1e-4)


class InteractionGate(nn.Module):
    """beta_pq(z): a sparse, signed weight on each pairwise coupling term.

    Sparsity is the point. Most pairs of interventions do not interact, and a dense
    quadratic term would both overfit and destroy interpretability. We therefore use a
    hard-concrete / L0-style stochastic gate: beta = s * m where m is a smoothly relaxed
    Bernoulli that can take EXACT zeros, so the model can report "this pair does not
    interact in this state" rather than "approximately zero".
    """

    def __init__(self, d, emb=32, hidden=64, temp=2.0 / 3.0,
                 stretch=(-0.1, 1.1), code=0):
        super().__init__()
        self.code = code
        self.amp = mlp(d + 2 * emb + code, hidden, 1, depth=2)
        self.logit = mlp(d + 2 * emb + code, hidden, 1, depth=2)
        nn.init.normal_(self.amp[-1].weight, std=1e-2); nn.init.zeros_(self.amp[-1].bias)
        nn.init.normal_(self.logit[-1].weight, std=1e-2)
        nn.init.constant_(self.logit[-1].bias, -1.0)   # start mostly closed
        self.temp, self.lo, self.hi = temp, stretch[0], stretch[1]

    def forward(self, z, e_p, e_q, sample=True, u=None):
        parts = [z, e_p, e_q]
        if self.code:
            parts.append(u.expand(z.shape[0], -1) if u.dim() == 1 else u)
        h = torch.cat(parts, -1)
        a = self.amp(h)
        la = self.logit(h)
        if sample and self.training:
            u = torch.rand_like(la).clamp(1e-6, 1 - 1e-6)
            s = torch.sigmoid((torch.log(u) - torch.log(1 - u) + la) / self.temp)
        else:
            s = torch.sigmoid(la / self.temp)
        s = s * (self.hi - self.lo) + self.lo
        m = s.clamp(0.0, 1.0)                     # EXACT zeros/ones possible
        return a * m, la

    def l0_penalty(self, la):
        """Expected number of open gates (differentiable) -- for the sparsity objective."""
        return torch.sigmoid(la - self.temp * math.log(-self.lo / self.hi)).mean()


class Connection(nn.Module):
    """Levi-Civita connection term Gamma(z)[u, v] of a learned metric, in Cholesky form.

    Why this exists: the naive symmetric coupling field is not a tensor, so a model built
    on it gives chart-dependent answers -- the same defect, one derivative up, that
    motivates composing fields instead of displacements. Including the connection makes the
    coupling term a genuine geometric object.

    We learn L(z) lower-triangular with positive diagonal, giving metric G = L L^T, and
    obtain Gamma[u,v] by automatic differentiation of G. Cost is O(d) JVPs; we keep d small
    (<= 16) precisely so this stays affordable.
    """

    def __init__(self, d, hidden=64, depth=2, eps=1e-3):
        super().__init__()
        self.d, self.eps = d, eps
        self.n_tri = d * (d + 1) // 2
        self.net = mlp(d, hidden, self.n_tri, depth=depth)
        nn.init.normal_(self.net[-1].weight, std=1e-2); nn.init.zeros_(self.net[-1].bias)
        idx = torch.tril_indices(d, d)
        self.register_buffer("tri_i", idx[0]); self.register_buffer("tri_j", idx[1])

    def metric(self, z):
        B = z.shape[0]
        vals = self.net(z)
        L = z.new_zeros(B, self.d, self.d)
        L[:, self.tri_i, self.tri_j] = vals
        diag = torch.arange(self.d, device=z.device)
        L[:, diag, diag] = torch.nn.functional.softplus(L[:, diag, diag]) + self.eps
        return L @ L.transpose(1, 2)

    def gamma(self, z, u, v):
        """Gamma(z)[u,v]^k = 1/2 G^{kl} (d_i G_lj + d_j G_li - d_l G_ij) u^i v^j.

        Implementation note. The third term needs d_l (G_ij u^i v^j) for every l. Doing
        that with one JVP per basis direction costs d forward passes and dominated runtime
        (measured: 270 s for 200 training steps at d=6). Instead we get all d components in
        ONE reverse-mode pass, because G_ij u^i v^j is a SCALAR per sample: its gradient
        w.r.t. z is exactly the vector we need. Cost drops from O(d) passes to O(1).
        """
        u = u.detach(); v = v.detach()
        z_ = z.detach().requires_grad_(True)

        def G_of(zz):
            return self.metric(zz)

        G = self.metric(z_)
        _, dG_u = torch.func.jvp(G_of, (z_,), (u,))
        _, dG_v = torch.func.jvp(G_of, (z_,), (v,))
        t1 = torch.einsum('blj,bj->bl', dG_u, v)
        t2 = torch.einsum('bli,bi->bl', dG_v, u)
        # t3_l = d_l (G_ij u^i v^j): one grad of a per-sample scalar
        with torch.enable_grad():
            quad = torch.einsum('bij,bi,bj->b', self.metric(z_), u, v).sum()
            t3, = torch.autograd.grad(quad, z_, create_graph=self.training)
        rhs = 0.5 * (t1 + t2 - t3)
        # solve G x = rhs with a jitter fallback: G is PD by construction but can be
        # ill-conditioned early in training, and a silent NaN here poisons the whole run.
        eyed = torch.eye(self.d, device=z.device, dtype=z.dtype).expand_as(G)
        out = torch.linalg.solve(G + 1e-6 * eyed, rhs.unsqueeze(-1)).squeeze(-1)
        return torch.nan_to_num(out, nan=0.0, posinf=0.0, neginf=0.0)


class ComposeFM(nn.Module):
    """The full operator. `mode` selects the ablation rung.

    mode:
      'additive'  X_P = sum_p tau_p X_p                      (covariant, no gate)
      'const'     X_P = g * sum_p tau_p X_p, g a scalar      (one global parameter)
      'gate'      X_P = gamma(z,P) * sum_p tau_p X_p         (state-dependent contraction;
                  gamma includes the saturating exposure factor unless saturate=False,
                  which isolates "does saturation matter?" from "does the gate matter?")
      'full'      'gate' + 1/2 sum beta_pq S^grad_pq         (+ covariant coupling)
    """

    def __init__(self, d, n_pert, emb=32, hidden=128, depth=3,
                 mode="full", use_connection=True, saturate=True, code=0,
                 field_limit=50.0):
        super().__init__()
        assert mode in ("additive", "const", "gate", "full")
        self.d, self.n_pert, self.mode, self.code = d, n_pert, mode, code
        self.pop = PopulationEncoder(d, code=code) if code else None
        self.gen = Generators(d, n_pert, emb=emb, hidden=hidden, depth=depth, code=code)
        self.gate = (ContractionGate(d, emb=emb, saturate=saturate, code=code)
                     if mode in ("gate", "full") else None)
        self.const = nn.Parameter(torch.tensor(2.2)) if mode == "const" else None
        self.inter = InteractionGate(d, emb=emb, code=code) if mode == "full" else None
        self.conn = Connection(d) if (mode == "full" and use_connection) else None
        # exposure scale at which the bilinear coupling term saturates (learned)
        self.log_kappa_c = (nn.Parameter(torch.tensor(1.0)) if mode == "full" else None)
        # trust-region multiple for the composed field (divergence guard, see field())
        self.field_limit = float(field_limit)

    # ---------------------------------------------------------------- field
    def field(self, z, ps, taus, collect=None, u=None):
        """X_P(z; u). ps: (k,) ids; taus: (B,k); u: population code -> (B,d)"""
        B = z.shape[0]
        fields = self.gen.all_fields(z, ps, u)                     # (B,k,d)
        drive = (taus.unsqueeze(-1) * fields).sum(1)               # (B,d)

        if self.mode == "additive":
            out = drive
        elif self.mode == "const":
            out = torch.sigmoid(self.const) * drive
        else:
            g = self.gate(z, fields, taus, u)                      # (B,1)
            out = g * drive
            if collect is not None:
                collect["gamma"] = g.detach()

        if self.mode == "full" and len(ps) > 1:
            # All pairs in ONE batched JVP rather than 2 JVPs per pair per substep.
            # Naive loop cost: n_pair * 2 JVPs * n_substeps (72 at k=3, 6 steps) -> 1381
            # ms/step. Batching over the pair axis makes it 2 JVPs per substep regardless
            # of k, by stacking the pair members along the batch dimension.
            pairs = [(a, b) for a in range(len(ps)) for b in range(a + 1, len(ps))]
            n_pair = len(pairs)
            ia = torch.tensor([a for a, _ in pairs], device=z.device)
            ib = torch.tensor([b for _, b in pairs], device=z.device)
            pid = torch.as_tensor([int(p) for p in ps], device=z.device)

            zr = z.repeat(n_pair, 1)                                  # (P*B, d)
            pa = pid[ia].repeat_interleave(B)                         # (P*B,)
            pb = pid[ib].repeat_interleave(B)
            Xa = fields[:, ia].permute(1, 0, 2).reshape(-1, self.d)   # (P*B, d)
            Xb = fields[:, ib].permute(1, 0, 2).reshape(-1, self.d)

            _, jb = torch.func.jvp(lambda zz: self.gen(zz, pb, u), (zr,), (Xa,))
            _, ja = torch.func.jvp(lambda zz: self.gen(zz, pa, u), (zr,), (Xb,))
            S = jb + ja
            if self.conn is not None:
                S = S + 2.0 * self.conn.gamma(zr, Xa, Xb)

            beta, la = self.inter(zr, self.gen.emb(pa), self.gen.emb(pb), u=u)
            # Exposure weight for the coupling term. The bilinear form tau_p * tau_q is
            # QUADRATIC in exposure, so outside the training range it overwhelms the
            # (saturating) first-order term: left unbounded it produced normalised energy
            # distances of ~1.4e6 at an 8.7x exposure extrapolation. The coupling must live
            # under the SAME saturation envelope as the drive, so we use the normalised
            # bilinear weight
            #        tau_p tau_q / (1 + T^2 / kappa_c^2),     T = sum tau,
            # which -> tau_p tau_q for small T (correct second-order behaviour, this is the
            # term's whole purpose) and -> bounded for large T. kappa_c is learned.
            tt = (taus[:, ia] * taus[:, ib]).permute(1, 0).reshape(-1, 1)  # (P*B,1)
            T = taus.clamp(min=0).sum(-1, keepdim=True)                    # (B,1)
            kc = torch.nn.functional.softplus(self.log_kappa_c) + 1e-3
            damp = 1.0 / (1.0 + (T / kc) ** 2)                             # (B,1)
            tt = tt * damp.repeat(n_pair, 1)
            coup = (beta * tt * S).view(n_pair, B, self.d).sum(0)
            out = out + 0.5 * coup
            if collect is not None:
                collect["l0"] = self.inter.l0_penalty(la)

        # Trust region on the composed field. S_pq contains a product of a Jacobian and a
        # field, so early in training -- before the L0 gate has learned which pairs are
        # inactive -- a single unlucky initialisation can make the coupling large enough
        # that the RK2 integrator diverges within one forward pass. Measured: with the
        # coupling active this happened at step 469 of 2500 on one of three seeds
        # (a k=2 population), the forward pass returned non-finite states, and the
        # subsequent optimiser step poisoned every weight, so the whole run reported NaN.
        # We therefore rescale (never clip componentwise, which would change the field's
        # DIRECTION in the current chart) any field whose norm exceeds a generous multiple
        # of the state scale.
        #
        # SCOPE OF THIS GUARD -- it is NOT a covariant operation. The rescale is keyed on
        # Euclidean norms of z and of the output, so like any norm-based clip it depends on
        # the chart: under a general diffeomorphism the set of states where it activates is
        # not preserved, and it would therefore break the exact covariance that the rest of
        # this operator is built to have. It also perturbs the exposure semigroup wherever
        # it activates, since the rescaled field is no longer the field whose flow was
        # being integrated. Both properties are verified elsewhere in the REGIME WHERE THE
        # GUARD IS INACTIVE, which is the regime of a trained model: on the checks in this
        # file the guard never activates (measured: field norms ~0.08 against a limit of
        # 50x the state norm). Treat it strictly as a numerical divergence guard on
        # pathological early-training iterates, not as part of the model definition; if it
        # activates in a trained model, that is a bug to investigate rather than a bound to
        # rely on.
        nrm = out.norm(dim=-1, keepdim=True)
        lim = self.field_limit * z.detach().norm(dim=-1, keepdim=True).clamp(min=1.0)
        out = torch.where(nrm > lim, out * (lim / nrm.clamp(min=1e-12)), out)
        return out

    # ---------------------------------------------------------------- flow
    def flow(self, z0, ps, taus, n_steps=8, collect=None, z_pop=None):
        """Integrate X_P for unit time with midpoint RK2 (exposure is inside taus).

        `z_pop` is the pre-intervention SAMPLE used to build the population code. It is
        encoded ONCE, before integration, and held fixed along the trajectory -- so each
        X_p(.; u) remains an autonomous field and the exposure semigroup is preserved.
        Defaults to z0 itself.
        """
        u = None
        if self.pop is not None:
            u = self.pop(z0 if z_pop is None else z_pop)
        z = z0
        h = 1.0 / n_steps
        for _ in range(n_steps):
            k1 = self.field(z, ps, taus, collect=collect, u=u)
            k2 = self.field(z + 0.5 * h * k1, ps, taus, u=u)
            z = z + h * k2
        return z


class DisplacementBaseline(nn.Module):
    """The class this paper is about: predict a DISPLACEMENT and add displacements.

    This is the structure shared by CPA- and GEARS-style latent perturbation models. It is
    a fair, trained baseline -- same trunk width, same budget -- differing only in the
    composition rule. Exposure enters as an input feature, which is the only way a
    displacement model can represent it.
    """

    def __init__(self, d, n_pert, emb=32, hidden=128, depth=3):
        super().__init__()
        self.emb = nn.Embedding(n_pert, emb)
        nn.init.normal_(self.emb.weight, std=0.1)
        self.net = mlp(d + emb + 1, hidden, d, depth=depth, ln=True)
        nn.init.zeros_(self.net[-1].weight); nn.init.zeros_(self.net[-1].bias)

    def predict(self, z0, ps, taus):
        out = z0
        for i, p in enumerate(ps):
            e = self.emb(torch.full((z0.shape[0],), int(p), device=z0.device,
                                    dtype=torch.long))
            t = taus[:, i:i + 1]
            out = out + t * self.net(torch.cat([z0, e, t], -1))
        return out
